name: CI/CD

on:
  push:
    branches:
      - 'main'

env:
  path: /var/www/histogram.nikolab131.xyz
  tempPath: /var/tmp/histogram.nikolab131.xyz

jobs:
  build:
    name: 'Build frontend and deploy backend'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Tests
        run: npm test
      - name: Clean previous files
        run: rm -rf ${{env.path}}
      - name: Copy backend
        run: |
          mkdir -p ${{env.path}}/node_modules/json-server
          cp -r node_modules/json-server/. ${{env.path}}/node_modules/json-server
          mkdir -p ${{env.path}}/json-server
          cp -r json-server/. ${{env.path}}/json-server
      - name: Deploy backend
        run: pm2 -s restart /var/configs/pm2_ecosystem.config.js --env production --only "Simple-histogram backend"
      - name: Build frontend
        run: |
          cp -r /var/environments/histogram.nikolab131.xyz/. .
          npm run build
      - name: Clean previous files
        run : rm -rf ${{env.tempPath}}
      - name: Copy frontend
        run: |
          mkdir -p ${{env.tempPath}}
          mkdir -p ${{env.tempPath}}/.next
          cp -r .next/* ${{env.tempPath}}/.next
          cp package.json ${{env.tempPath}}
          cp package-lock.json ${{env.tempPath}}
          cp -r /var/environments/histogram.nikolab131.xyz/. ${{env.tempPath}}

  deploy:
    needs: build
    name: 'Deploy frontend'
    runs-on: self-hosted

    steps:
      - name: Copy
        run: |
          mkdir -p ${{env.path}}
          cp -r ${{env.tempPath}}/. ${{env.path}}
      - name: Install dependencies
        run: |
          cd ${{env.path}}
          npm ci
      - name: Restart pm2
        run: pm2 -s restart /var/configs/pm2_ecosystem.config.js --env production
      - name: Save pm2
        run: pm2 -s save
